# Generated by Django 4.1.1 on 2022-10-13 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_post_likers'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='does_like',
            field=models.BooleanField(default=False),
        ),
    ]
